// Generates src/environments/keys.ts from .env so keys never live in committed source.
// Runs automatically before `yarn start` / `yarn build`.
const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
if (!fs.existsSync(envPath)) {
  console.error('Missing front/.env - copy .env.example to .env and fill in your keys.');
  process.exit(1);
}
process.loadEnvFile(envPath);

const required = ['FIREBASE_API_KEY'];
const missing = required.filter((name) => !process.env[name]);
if (missing.length > 0) {
  console.error(`Missing values in front/.env: ${missing.join(', ')}`);
  process.exit(1);
}

const content = `// Generated by set-env.js from .env - do not edit or commit.
export const keys = {
  firebaseApiKey: ${JSON.stringify(process.env.FIREBASE_API_KEY)},
};
`;
fs.writeFileSync(path.join(__dirname, 'src', 'environments', 'keys.ts'), content);
console.log('Wrote src/environments/keys.ts from .env');
